packages:
  - "packages/nocodb-sdk"
  - "packages/nocodb-sdk-v2"
  - "packages/nc-gui"
  - "packages/nc-gui-product"
  - "packages/nc-product-matching"
  - "packages/nc-mail-templates"
  - "packages/nocodb"
  - "tests/playwright"
  - "packages/nc-secret-mgr"
